- postman/xs2a gateway (adorsys-integ) .postman_environment.json
- postman/xs2a gateway (consors-bank).postman_environment.json
- postman/xs2a gateway (dab-bank).postman_environment.json
- postman/xs2a gateway (deutsche-bank).postman_environment.json
- postman/xs2a gateway (sparkasse).postman_environment.json
- postman/xs2a gateway (verlag).postman_environment.json
- postman/xs2a gateway.postman_collection.json
To avoid cross product between number of adapters and gateway environments.
>  Remove baseUri from postman adapter environments

- xs2a-adapter-app/src/test/de/adorsys/xs2a/adapter/controller/ConsentControllerWebMvcTest.java
- xs2a-adapter-app/src/test/de/adorsys/xs2a/adapter/controller/PaymentControllerWebMvcTest.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/AccountAccessTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/AccountDetailsTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/AccountStatusTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/AuthenticationTypeTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/BalanceTypeTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/BookingStatusTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/ChallengeDataTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/ConsentStatusTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/DayOfExecutionTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/ExecutionRuleTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/FrequencyCodeTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/MessageCode2XXTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/MessageCodeTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/PaymentProductTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/PaymentServiceTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/PurposeCodeTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/ScaStatusTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/TppMessageCategoryTO.java
- xs2a-adapter-psd2-api/src/main/java/de/adorsys/xs2a/adapter/model/TransactionStatusTO.java
- xs2a-adapter-rest-impl/src/main/java/de/adorsys/xs2a/adapter/config/RestExceptionHandler.java
- xs2a-adapter-rest-impl/src/test/java/de/adorsys/xs2a/adapter/controller/ConsentControllerTest.java
- xs2a-adapter-rest-server/src/main/java/de/adorsys/xs2a/adapter/config/PropertyEditorControllerAdvice.java
PropertyEditors look like the only possible way to prevent the fallback
to default conversion logic that tries to match a string against enum
fields.
> Fix NPEs in controllers when calling endpoints with illegal enum values

- postman/xs2a adapter.postman_collection.json
For unicredit authoriseTransaction link returned after
startAuthorisationWithPsuAuthentication request
> Fix uninitialized authorisationId in psd2/ais collection

- devops/charts/env/integ/env.yaml
- devops/charts/templates/xs2a-adapter/deployment.yaml
Causes an error during installation
Error: render error in "xs2a-adapter/templates/xs2a-adapter/deployment.yaml": template: xs2a-adapter/templates/xs2a-adapter/deployment.yaml:17:26: executing "xs2a-adapter/templates/xs2a-adapter/deployment.yaml" at <include (print $.Tem...>: error calling include: template: xs2a-adapter/templates/xs2a-adapter/configmap.yaml:10:28: executing "xs2a-adapter/templates/xs2a-adapter/configmap.yaml" at <.Values.logback.file>: invalid value; expected string
> Fix integ helm values, deploymentConfig template

- xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/model/PaymentInitiationAuthorisationResponse.java
Without setter mapstruct will not copy 'authorisationIds' list to PaymentInitiationAuthorisationResponse from AuthorisationsTO because 'authorisationIds' is null on target.
> `xs2a-adapter-service-api` - add setter for PaymentInitiationAuthorisationResponse.authorisationIds

- adapters/verlag-adapter/src/main/java/de/adorsys/xs2a/adapter/service/provider/VerlagServiceProvider.java
- xs2a-adapter-service-api-adapter/src/main/java/de/adorsys/xs2a/adapter/http/ApacheHttpClientFactory.java
- xs2a-adapter-service-api-adapter/src/test/java/de/adorsys/xs2a/adapter/http/ApacheHttpClientFactoryTest.java
- xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/http/HttpClientFactory.java
TLS handshake with production server of bank-verlag fails because Diffie-Hellman
key length is 1024 bits. While minimum recommended is 2048.
The server also ranks DHE key exchange algorithm above ECDHE that stronger.
As a solution limit supported cipher suites of the client to strong cipher suites
supported by production and sandbox servers.
> Fix bank-verlag's "DHPublicKey does not comply to algorithm constraints"

- xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/model/ErrorResponse.java
```json
{
"tppMessages" : [ {
"category" : "ERROR",
"code" : "BAD_REQUEST",
"text" : "Consent with empty access/accounts not supported."
} ],
"empty" : false
}
```
> `xs2a-adapter-rest-impl` - ErrorResponse - add @JsonIgnore to 'isEmpty' method because "empty" property is returned in response JSON, e.g.:

- xs2a-adapter-aspsp-registry/src/main/java/de/adorsys/xs2a/adapter/registry/LuceneAspspRepositoryFactory.java
MD5 is no longer required since Java 14
https://github.com/openjdk/jdk/commit/b171594072659cd9914c0f211156f4af3e2b0550#diff-7de55d11c146a664ea77257279945551
> Change csv file digest algorithm from md5 to sha-256

- .github/workflows/develop.yml
1) Proposal to unify the docker build into a separate step:
For specifying the environment in which the image should be used `docker tag` is used before `docker push`.
2) `docker login` separated, `docker logout` added.
> Refactor Docker Deployment

- docs/release_notes/DRAFT_Release_notes_0.0.9.adoc
Was raised back to 44 by the previous commit.
> Remove sparda code verifier length change from release notes

- xs2a-adapter-aspsp-registry/src/main/resources/aspsp-adapter-config.csv
The AMOS-Project needs additional banks to simulate different scenarios while developing the process miner.
The UUIDs were created using `uuidgen`. If there is anything that has to be adjusted just let me know.
> Add dummy banks for process miner development

- adapters/ing-adapter/src/main/java/de/adorsys/xs2a/adapter/ing/IngClientAuthenticationFactory.java
- xs2a-adapter-aspsp-registry/src/main/java/de/adorsys/xs2a/adapter/registry/LuceneAspspRepositoryFactory.java
- xs2a-adapter-service-api-adapter/src/main/java/de/adorsys/xs2a/adapter/signing/service/hashing/AbstractShaHashingService.java
- xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/PkceOauth2Extension.java
https://rules.sonarsource.com/java/RSPEC-4790
Hashing is performed according to the specification of a standard
(pkce/request signature) or used in non-security related context.
> Suppress hashing security hotspots detected by sonar

- docs/arc42/puml/whitebox_lv1_library.puml
- docs/arc42/puml/whitebox_lv1_stanalone.puml
- docs/arc42/sections/5_building_block_view.adoc
Also updated the rest of the library component diagram according to the
conventional meaning of the ball and socket notation.
> symbols with a complete circle at their end represent an interface
> that the component provides — this “lollipop” symbol is shorthand for
> a realization relationship of an interface classifier. Interface
> symbols with only a half circle at their end (a.k.a. sockets)
> represent an interface that the component requires (in both cases, the
> interface’s name is placed near the interface symbol itself).
> - https://developer.ibm.com/articles/the-component-diagram/
And renamed component labels:
* "service-api-adapter" to "service-impl";
* "bank adapters" to "adapters": matching the maven module name;
* "Banks" to "ASPSPs": consistent terminology with …
> Document csv and properties file dependencies in the Building Block View

- adapters/deutsche-bank-adapter/src/main/java/de/adorsys/xs2a/adapter/deutschebank/PsuIdTypeHeaderInterceptor.java
- adapters/deutsche-bank-adapter/src/test/java/de/adorsys/xs2a/adapter/deutschebank/PsuIdTypeHeaderInterceptorTest.java
- docs/release_notes/DRAFT_Release_notes_0.1.3.adoc
Completes the migration started in the previous release.
> Remove PFB business entity support in db adapter

- adapters/consors-bank-adapter/src/main/java/de/adorsys/xs2a/adapter/consors/ConsorsAccountInformationService.java
- adapters/consors-bank-adapter/src/test/java/de/adorsys/xs2a/adapter/consors/ConsorsAccountInformationServiceTest.java
- docs/release_notes/DRAFT_Release_notes_0.1.3.adoc
> Accept header is mandatory, and the only accepted value is "application/json"
> - https://www.consorsbank.de/content/dam/de-cb/editorial/PDF/Service-Beratung/xs2a/xs2a-nextgen-psd2-framework-20200909.yaml
> Set Accept header for get transactions, consors

- adapters/crealogix-adapter/src/main/java/de/adorsys/xs2a/adapter/crealogix/CrealogixEmbeddedPreAuthorisationService.java
- adapters/crealogix-adapter/src/main/java/de/adorsys/xs2a/adapter/crealogix/CrealogixMapper.java
- adapters/crealogix-adapter/src/main/java/de/adorsys/xs2a/adapter/crealogix/model/CrealogixActionCode.java
- adapters/crealogix-adapter/src/main/java/de/adorsys/xs2a/adapter/crealogix/model/CrealogixAuthItem.java
- adapters/crealogix-adapter/src/main/java/de/adorsys/xs2a/adapter/crealogix/model/CrealogixAuthType.java
- adapters/crealogix-adapter/src/main/java/de/adorsys/xs2a/adapter/crealogix/model/CrealogixReturnCode.java
- adapters/crealogix-adapter/src/main/java/de/adorsys/xs2a/adapter/crealogix/model/CrealogixValidationResponse.java
- adapters/crealogix-adapter/src/test/java/de/adorsys/xs2a/adapter/crealogix/CrealogixEmbeddedPreAuthorisationServiceTest.java
DKB has its own custom model for *POST /psd2-auth/v1/auth/token* request
https://api.dkb.de/store/apis/info?name=PSD2Pre-StepAuthorizationAPI&version=1.0.6&provider=admin#/PSD2-Auth/ValidateCredentials
Missing models were added and mappers created for proper resolving
> added CrealogixValidationResponse model for DKB 

- adapters/unicredit-adapter/src/main/java/de/adorsys/xs2a/adapter/unicredit/UnicreditMapper.java
- adapters/unicredit-adapter/src/main/java/de/adorsys/xs2a/adapter/unicredit/UnicreditPaymentInitiationService.java
- adapters/unicredit-adapter/src/main/java/de/adorsys/xs2a/adapter/unicredit/model/UnicreditUpdatePsuAuthenticationResponse.java
- adapters/unicredit-adapter/src/test/java/de/adorsys/xs2a/adapter/unicredit/UnicreditPaymentInitiationServiceTest.java
- docs/release_notes/DRAFT_Release_notes_0.1.14.adoc
The UniCredit Group returns an invalid response format for updating the psu data for payments:
```json
"_links" : [ {
"authoriseTransaction" : {
"href" : "..."
}
} ]
```
is returned instead of
```json
"_links" : {
"authoriseTransaction" : {
"href" : "..."
}
}
```
The UniCredit support suggested to manage the API response as provided from their system until the fix will be ready for production environment. The final technical solution will require time to be implemented.
This pull request contains a workaround for this problem that needs to be reverted after the UniCredit released the final technical solution.
> fix unicredit-adapter update payment psu data failing because of invalid links format in response

- adapters/deutsche-bank-adapter/src/main/java/de/adorsys/xs2a/adapter/deutschebank/DeutscheBankServiceProvider.java
- adapters/deutsche-bank-adapter/src/main/java/de/adorsys/xs2a/adapter/deutschebank/PsuIdHeaderInterceptor.java
- adapters/deutsche-bank-adapter/src/test/java/de/adorsys/xs2a/adapter/deutschebank/PsuIdHeaderInterceptorTest.java
- docs/release_notes/DRAFT_Release_notes_0.1.14.adoc
The user ID of DE/DB and DE/Noris is composed as follows:
- 3 digit branch number
- 7 digit account number
- 2 digit subaccount number
The subaccount number is **not** part of the PSU-ID for XS2A.
I implemented an interceptor that removes the subaccount number for DE/DB and DE/Noris from the PSU-ID if necessary.
For more information, see Technical Documentation Chapter 9.3.2.
> remove subaccount number from PSU-ID for DE/DB and DE/Noris

- adapters/crealogix-adapter/README.md
- docs/developer_guide.md
- docs/release_notes/DRAFT_Release_notes_0.1.15.adoc
- xs2a-adapter-aspsp-registry/src/main/resources/aspsp-adapter-config.csv
Implying from the bank documentation, the existing `dkb-adapter` should perfectly work for all Aareal banks, thus only a record with Aareal information is needed and it was added to the CSV with `dkb-adapter` ID.
> Add Aareal Bank

- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-create-consent.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-delete-consent.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-get-accounts.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-get-consent-status.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-get-sca-status.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-get-transactions.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-select-sca-method.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-send-otp.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/ais-start-psu-authentication.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-pain001-sct-get-payment-status.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-pain001-sct-get-sca-status.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-pain001-sct-initiate-payment.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-pain001-sct-select-sca-method.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-pain001-sct-send-otp.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-pain001-sct-start-psu-authentication.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-sct-get-payment-status.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-sct-get-sca-status.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-sct-initiate-payment.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-sct-select-sca-method.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-sct-send-otp.json
- adapters/sparkasse-adapter/src/main/resources/sparkasse-adapter/mappings/pis-payments-sct-start-psu-authentication.json
- adapters/sparkasse-adapter/src/test/resources/ais/select-sca-method.json
- adapters/sparkasse-adapter/src/test/resources/pis/payments/sepa-credit-transfers/select-sca-method.json
- docs/release_notes/DRAFT_Release_notes_0.1.16.adoc
Sparkasse stubs were configured to comfort tests only but don't work in WireMock mode. Fixed that.
> Fix sparkasse wiremock stubs

- adapters/fiducia-adapter/src/main/java/de/adorsys/xs2a/adapter/fiducia/FiduciaAccountInformationService.java
- adapters/fiducia-adapter/src/test/java/de/adorsys/xs2a/adapter/fiducia/FiduciaAccountInformationServiceTest.java
Add new supported booking status to FiduciaAccountInformationService,
add test to check supported statuses validation
> Extending Fiducia booking statuses list 
