deutsche-bank-adapter/src/main/java/de/adorsys/xs2a/gateway/service/impl/DeutscheBankPaymentService.java, xs2a-gateway-app/src/main/java/de/adorsys/xs2a/gateway/config/RestConfiguration.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/controller/PaymentController.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/mapper/PaymentInitiationScaStatusResponseMapper.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/model/pis/ScaStatusTO.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/model/shared/ScaStatusResponse.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/model/shared/StartScaprocessResponse.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/PaymentInitiationScaStatusHeaders.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/PaymentInitiationScaStatusResponse.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/PaymentService.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/ScaStatus.java, xs2a-gateway-service-impl/src/main/java/de/adorsys/xs2a/gateway/service/impl/PaymentServiceImpl.java
Please, take a look at our first mapper: the module, the package name, the code style, etc.
=> Get authorisation status flow

xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/ScaStatus.java
E.g. psuAuthenticated instead of PSUAUTHENTICATED
=> Fix case sensitive serialization of SCA status

deutsche-bank-adapter/src/main/java/de/adorsys/xs2a/gateway/service/impl/DeutscheBankAccountInformationService.java, deutsche-bank-adapter/src/test/java/de/adorsys/xs2a/gateway/service/impl/DeutscheBankAccountInformationServiceTest.java, xs2a-gateway-app/src/main/java/de/adorsys/xs2a/gateway/config/RestExceptionHandler.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/config/BankCodeFilter.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/controller/AbstractController.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/controller/ConsentController.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/controller/PaymentController.java, xs2a-gateway-rest-server/src/main/java/de/adorsys/xs2a/gateway/mapper/HeadersMapper.java, xs2a-gateway-rest-server/src/test/java/de/adorsys/xs2a/gateway/controller/ConsentControllerTest.java, xs2a-gateway-service-api-adapter/src/main/java/de/adorsys/xs2a/gateway/adapter/AbstractService.java, xs2a-gateway-service-api-adapter/src/main/java/de/adorsys/xs2a/gateway/adapter/BaseAccountInformationService.java, xs2a-gateway-service-api-adapter/src/main/java/de/adorsys/xs2a/gateway/adapter/BasePaymentInitiationService.java, xs2a-gateway-service-api-adapter/src/main/java/de/adorsys/xs2a/gateway/http/ApacheHttpClient.java, xs2a-gateway-service-api-adapter/src/main/java/de/adorsys/xs2a/gateway/http/HttpClient.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/GeneralResponse.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/PaymentInitiationService.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/RequestHeaders.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/ResponseHeaders.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/ais/AccountInformationService.java, xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/exception/ErrorResponseException.java, xs2a-gateway-service-loader/src/main/java/de/adorsys/xs2a/gateway/service/impl/AccountInformationServiceImpl.java, xs2a-gateway-service-loader/src/main/java/de/adorsys/xs2a/gateway/service/impl/PaymentInitiationServiceImpl.java, xs2a-gateway-service-loader/src/test/java/de/adorsys/xs2a/gateway/service/impl/ConsentServiceImplTest.java
- provided GeneralResponse class to be used as a response wrapper for each service method;
- separated headers into RequestHeaders and ResponseHeaders classes;
- updated the flow to make it work with new classes.
=> Fixed missing response headers

xs2a-gateway-app/src/main/java/de/adorsys/xs2a/gateway/config/RestExceptionHandler.java
Exceptions to handle:
- UncheckedIOException;
- UnsupportedOperationException;
- Exception.
=> Extended exception handling for the new exceptions

xs2a-gateway-service-api/src/main/java/de/adorsys/xs2a/gateway/service/Links.java
An error occurs during deserialization
`java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
at [Source: (PushbackInputStream); line: 1, column: 108] (through reference chain: de.adorsys.xs2a.gateway.service.ErrorResponse["_links"]->de.adorsys.xs2a.gateway.service.Links["scaStatus"])
`
=> Fix links deserialization in error response

adapters/sparda-bank-adapter/src/main/java/de/adorsys/xs2a/gateway/service/provider/SpardaServiceProvider.java
=> Update sparda sandbox url

xs2a-adapter-service-api-adapter/src/main/java/de/adorsys/xs2a/adapter/signing/storage/KeyStorageService.java
…stem property is not provided)
=> Fixed NPE during KeyStorageService initialisation

xs2a-adapter-service-loader/src/main/resources/aspsp-adapter-config.csv
config for netbank and 1822direkt
=> Ba fork 1822 config

postman/xs2a adapter (adorsys-integ).postman_environment.json, xs2a-adapter-aspsp-registry/src/main/resources/aspsp-adapter-config.csv
=> Adorsys sandbox adapter

xs2a-adapter-aspsp-registry/src/main/java/de/adorsys/xs2a/adapter/registry/LuceneAspspRepository.java, xs2a-adapter-aspsp-registry/src/test/java/de/adorsys/xs2a/adapter/registry/LuceneAspspRepositoryTest.java
Caused by `findById` used in `save`
=> Fix IndexNotFoundException on creation of index from file

xs2a-adapter-service-remote/pom.xml, xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/ErrorResponseDecoder.java, xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/RestExceptionHandler.java, xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/TppApplication.java
https://github.com/spring-cloud/spring-cloud-netflix/issues/1811
https://bugs.openjdk.java.net/browse/JDK-8052118
=> Add custom error decoder example, use apache http client for feign

xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/ErrorResponseDecoder.java
https://github.com/adorsys/xs2a-adapter/pull/171#discussion_r320214722
=> Read response body via reader instead of toString

xs2a-adapter-rest-api/src/main/java/de/adorsys/xs2a/adapter/api/Oauth2Api.java, xs2a-adapter-rest-impl/src/main/java/de/adorsys/xs2a/adapter/controller/Oauth2Controller.java, xs2a-adapter-service-remote/src/main/java/de/adorsys/xs2a/adapter/api/remote/Oauth2Client.java, xs2a-adapter-service-remote/src/main/java/de/adorsys/xs2a/adapter/api/remote/psd2/Psd2AccountInformationClient.java, xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/AppConfiguration.java, xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/controller/Oauth2Controller.java, xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/controller/Psd2AccountInformationController.java
Changed getAuthorizationUrl parameter from URI to String because of feign
request line override
=> Add feign clients for  Psd2AccountInformationApi and Oauth2Api

README.md, adapters/dkb-adapter/src/main/java/de/adorsys/xs2a/adapter/service/impl/DkbAccessTokenService.java, adapters/dkb-adapter/src/test/java/de/adorsys/xs2a/adapter/service/impl/DkbAccessTokenServiceTest.java, adapters/dkb-adapter/src/test/java/de/adorsys/xs2a/adapter/service/provider/DkbServiceProviderTest.java, adapters/dkb-adapter/src/test/resources/external.adapter.config.properties, adapters/verlag-adapter/src/main/java/de/adorsys/xs2a/adapter/service/impl/VerlagAccountInformationService.java, adapters/verlag-adapter/src/main/java/de/adorsys/xs2a/adapter/service/impl/VerlagPaymentInitiationService.java, adapters/verlag-adapter/src/main/java/de/adorsys/xs2a/adapter/service/provider/VerlagServiceProvider.java, devops/charts/env/banking-gateway-dev/env.yaml, devops/charts/env/banking-gateway-integ/env.yaml, devops/charts/env/develop/env.yaml, devops/charts/templates/xs2a-adapter/deployment.yaml, devops/charts/templates/xs2a-adapter/pvc.yaml, docs/release_notes/DRAFT_Release_notes_0.0.4.adoc, xs2a-adapter-app/src/main/resources/application.yml, xs2a-adapter-service-api/pom.xml, xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/PropertyUtil.java, xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/config/AdapterConfig.java, xs2a-adapter-service-api/src/main/resources/adapter.config.properties, xs2a-adapter-service-api/src/test/java/de/adorsys/xs2a/adapter/service/PropertyUtilTest.java, xs2a-adapter-service-api/src/test/java/de/adorsys/xs2a/adapter/service/config/AdapterConfigTest.java, xs2a-adapter-service-api/src/test/resources/external.adapter.config.properties
to decrease the complexity of configuring the adapter, all application settings were moved to the config file
=> move adapters settings into config file

xs2a-adapter-rest2api-mapper/src/main/java/de/adorsys/xs2a/adapter/mapper/psd2/Oauth2Mapper.java, xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/Pkcs12KeyStore.java, xs2a-adapter-service-remote/src/main/java/de/adorsys/xs2a/adapter/service/impl/Oauth2ServiceImpl.java, xs2a-adapter-service-remote/src/main/java/de/adorsys/xs2a/adapter/service/impl/PaymentInitiationServiceImpl.java
xs2a-adapter-rest2api-mapper:
Add additional method to Oauth2Mapper
xs2a-adapter-service-api:
Add additional constructors for Pkcs12KeyStore
xs2a-adapter-service-remote:
Fixed bug in PaymentInitiationServiceImpl, added Oatuh2ServiceImpl
=> Small fixes

adapters/maven-adapter-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, adapters/maven-adapter-archetype/src/main/resources/archetype-resources/pom.xml
- updated the list of exclusions in maven-adapter-archetype pom.xml;
- updated project version in maven-adapter-archetype archetype-metadata.xml.
=> Maven archetype fix

docs/release_notes/DRAFT_Release_notes_0.0.4.adoc, xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/model/AccountAccess.java
xs2a-adapter-service-api`. AccountDetails - add missing @JsonValue annotations for AvailableAccountsEnum and AllPsd2Enum
=> Small fix of AccountAccess model

devops/charts/templates/xs2a-adapter/configmap.yaml
forgot to add file afte rename
=> add configmap file after rename

devops/README.md, devops/charts/config/banking-gateway-dev/logback.xml, devops/charts/config/banking-gateway-integ/logback.xml, devops/charts/env/banking-gateway-dev/env.yaml, devops/charts/env/banking-gateway-integ/env.yaml, devops/charts/env/develop/env.yaml, devops/charts/env/integ/env.yaml, devops/charts/templates/xs2a-adapter/configmap.yaml, devops/charts/templates/xs2a-adapter/deployment.yaml, devops/charts/templates/xs2a-adapter/pvc.yaml, devops/charts/values.yaml
https://kubernetes.io/docs/concepts/configuration/overview/#general-configuration-tips
=> Use configmap for all configuration to keep it under version control

adapters/pom.xml, docs/release_notes/DRAFT_Release_notes_0.0.5.adoc, docs/release_notes/Release_notes_0.0.4.adoc, xs2a-adapter-rest-api/src/main/java/de/adorsys/xs2a/adapter/rest/psd2/Psd2AccountInformationApi.java, xs2a-adapter-rest-impl/src/main/java/de/adorsys/xs2a/adapter/controller/Psd2AccountInformationController.java, xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/psd2/Psd2AccountInformationService.java, xs2a-adapter-service-api/src/main/java/de/adorsys/xs2a/adapter/service/psd2/Psd2AccountInformationServiceFactory.java, xs2a-adapter-service-remote/src/main/java/de/adorsys/xs2a/adapter/remote/api/psd2/Psd2AccountInformationClient.java, xs2a-adapter-service-remote/src/test/java/de/adorsys/xs2a/tpp/controller/Psd2AccountInformationController.java
have created a task to remove deprecated stuff for release 0.0.6
https://jira.adorsys.de/browse/XS2AAD-94
=> mark PSD2 API as deprecated. add draft release notes

xs2a-adapter-app/src/main/resources/logback-dev.xml
- amount
- remittanceInformationUnstructured
- creditorName
- iban
- creditorId
- debtorName
- mandateId
- endToEndId
=> Mask additional json fields with sensitive information in the wire log

.travis.yml, devops/build/deploy.sh, pom.xml
```
before
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:23 min
[INFO] Finished at: 2019-12-28T17:23:57+02:00
[INFO] ------------------------------------------------------------------------
real    1m24.266s
user    4m40.558s
sys     0m16.008s
after
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  52.404 s
[INFO] Finished at: 2019-12-28T17:26:36+02:00
[INFO] ------------------------------------------------------------------------
real    0m53.482s
user    2m53.522s
sys     0m10.576s
```
=> Skip jacoco by default to lower local build time

adapters/sparda-bank-adapter/src/main/java/de/adorsys/xs2a/adapter/service/SpardaOauth2Service.java, docs/release_notes/DRAFT_Release_notes_0.0.7.adoc, xs2a-adapter-app/src/main/java/de/adorsys/xs2a/adapter/config/AuditHandlerInterceptor.java, xs2a-adapter-app/src/main/resources/application.yml, xs2a-adapter-app/src/main/resources/logback-dev.xml, xs2a-adapter-aspsp-registry/src/main/java/de/adorsys/xs2a/adapter/registry/LuceneAspspRepository.java, xs2a-adapter-service-api-adapter/src/main/java/de/adorsys/xs2a/adapter/adapter/BaseOauth2Service.java, xs2a-adapter-service-api-adapter/src/main/java/de/adorsys/xs2a/adapter/http/Xs2aHttpLogSanitizer.java
- removed audit logging on the xs2a-adapter app side;
- provided logging for the calls being resolved on the adapter side without interaction with the bank.
=> Logs flow adjusting

adapters/adorsys-integ-adapter/src/main/java/de/adorsys/xs2a/adapter/adorsys/service/provider/AdorsysIntegServiceProvider.java, docs/release_notes/DRAFT_Release_notes_0.0.8.adoc, xs2a-adapter-service-api/src/main/resources/adapter.config.properties
=> Add request signing for adorsys adapter behind feature flag #367

adapters/dkb-adapter/src/main/java/de/adorsys/xs2a/adapter/service/provider/DkbServiceProvider.java, adapters/santander-adapter/src/main/java/de/adorsys/xs2a/adapter/service/provider/SantanderServiceProvider.java, docs/release_notes/DRAFT_Release_notes_0.0.8.adoc
https://github.com/adorsys/xs2a-adapter/issues/366
=> Fix DKB, Santander service providers init exceptions due to missing config

xs2a-adapter-codegen/README.md, xs2a-adapter-codegen/src/main/java/de/adorsys/xs2a/adapter/codegen/Main.java, xs2a-adapter-rest-impl/src/main/resources/static/xs2aapi.json
Changed locations for generated files to avoid manual copying.
=> Update xs2a openapi file with card-account operations

adapters/sparda-bank-adapter/src/main/java/de/adorsys/xs2a/adapter/service/SpardaOauth2Service.java, adapters/sparda-bank-adapter/src/main/java/de/adorsys/xs2a/adapter/service/SpardaPkceOauth2Service.java, adapters/sparda-bank-adapter/src/test/java/de/adorsys/xs2a/adapter/service/SpardaPkceOauth2ServiceTest.java, pom.xml
Updated assertj version due to a bug in `hasSizeBetween`
=> Add sparda code verifier length customization

docs/release_notes/DRAFT_Release_notes_0.0.10.adoc, xs2a-adapter-service-loader/src/main/java/de/adorsys/xs2a/adapter/service/loader/mapper/Xs2aPsd2Mapper.java, xs2a-adapter-service-loader/src/test/java/de/adorsys/xs2a/adapter/service/loader/mapper/Xs2aPsd2MapperTest.java
service layer enum toString doesn't produce spec values
=> Fix TransactionStatus mapping for psd2 api

docs/release_notes/DRAFT_Release_notes_0.0.10.adoc, xs2a-adapter-service-api-adapter/src/main/java/de/adorsys/xs2a/adapter/http/ResponseHandlers.java
java.io.UncheckedIOException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
=> Fix empty response body causes an exception

adapters/fiducia-adapter/src/main/java/de/adorsys/xs2a/adapter/fiducia/mapper/FiduciaMapper.java, adapters/fiducia-adapter/src/main/java/de/adorsys/xs2a/adapter/fiducia/model/FiduciaExchangeRate.java, adapters/fiducia-adapter/src/main/java/de/adorsys/xs2a/adapter/fiducia/model/FiduciaTransactionDetails.java, adapters/fiducia-adapter/src/test/java/de/adorsys/xs2a/adapter/fiducia/mapper/FiduciaMapperTest.java, docs/release_notes/DRAFT_Release_notes_0.1.1.adoc
https://jira.adorsys.de/browse/XS2AAD-611
=> Add ReportExchangeRate mapping in fiducia adapter

.github/workflows/banking-gateway.yml, pom.xml
This PR adds a maven profile with an additional dependency (org.codehaus.janino).
Since we need to have logging enabled to debug the integration of new banks this extension is needed to filter outgoing requests from logging.
=> Extended Logging and Corresponding Filters

adapters/ing-adapter/src/main/java/de/adorsys/xs2a/adapter/ing/IngMapper.java, adapters/ing-adapter/src/test/java/de/adorsys/xs2a/adapter/ing/IngMapperTest.java, adapters/ing-adapter/src/test/resources/pis/periodic-payments/sepa-credit-transfers/get-payment-status.json, docs/release_notes/DRAFT_Release_notes_0.1.2.adoc
=> Change ing's periodic payment status mapping values

README.md
… under Use As Library section
=> Add whitelist notation into README

adapters/comdirect-adapter/src/main/java/de/adorsys/xs2a/adapter/comdirect/ComdirectOauth2Service.java, adapters/comdirect-adapter/src/main/java/de/adorsys/xs2a/adapter/comdirect/ComdirectServiceProvider.java, adapters/comdirect-adapter/src/test/java/de/adorsys/xs2a/adapter/comdirect/ComdirectOauth2ServiceTest.java, docs/release_notes/DRAFT_Release_notes_0.1.8.adoc
Additionally updated ComdirectServiceProvider - leftover from the previous task #560
=> fixed comdirect authorization request link construction

docs/release_notes/DRAFT_Release_notes_0.1.9.adoc, xs2a-adapter-codegen/src/main/java/de/adorsys/xs2a/adapter/codegen/Header.java, xs2a-adapter-codegen/src/main/java/de/adorsys/xs2a/adapter/codegen/Main.java, xs2a-adapter-generated-api/src/main/java/de/adorsys/xs2a/adapter/api/model/TransactionDetailsBody.java, xs2a-adapter-generated-api/src/main/java/de/adorsys/xs2a/adapter/api/model/Transactions.java, xs2a-adapter-generated-rest-api/src/main/java/de/adorsys/xs2a/adapter/rest/api/ConsentApi.java, xs2a-adapter-rest-impl/src/main/java/de/adorsys/xs2a/adapter/rest/impl/controller/ConsentController.java, xs2a-adapter-rest-impl/src/main/resources/static/xs2aapi.json
https://jira.adorsys.de/browse/XS2AAD-803 
additionally completed https://jira.adorsys.de/browse/XS2AAD-805
=> Adjust code generator 

docs/arc42/sections/10_quality_requirements.adoc, docs/arc42/sections/11_risks_and_technical_debts.adoc, docs/release_notes/DRAFT_Release_notes_0.1.15.adoc
=> Added Risks and Technical Debts to the adapter arc42 document
